export type { components, operations, paths } from './openapi'

type Schemas = import('./openapi').components['schemas']

export type ChatV2Summary = Schemas['ChatSummary']
export type ChatBranchSummary = Schemas['BranchSummary']
export type ChatMessageNode = Schemas['ChatMessageView']
export type ChatConversationTree = Schemas['ConversationTreeView']
export type ChatMessagePathPage = Schemas['MessagePathPage']
export type ChatListPage = Schemas['ChatListPage']
export type ChatTurnCommand = Schemas['TurnCommand']
export type ChatTurnCreationResult = Schemas['TurnCreationResult']
export type ChatTurnAction = Schemas['TurnAction']
export type ChatForkReason = Schemas['ForkReason']
export type ChatMessageStatus = Schemas['MessageStatus']
export type GenerationStatus = Schemas['GenerationStatus']
export type MessageFeedbackRating = Schemas['MessageFeedbackRating']
export type MessageFeedback = Schemas['MessageFeedbackView']
export type ChatMatchRunSummary = Schemas['MatchRunSummary']
export type GenerationRun = Schemas['GenerationRunView']
